# frozen_string_literal: true

# What Rails accepts, written down so the frontend can be held to it (#164).
#
# The wizard's input validation is the one piece of it that is duplicated
# rather than exported: the frontend has to decide what may go into a command
# before it renders one, and it cannot ask Rails at that moment. A duplicate is
# a thing that drifts, so this writes Rails' answers for a list of inputs --
# the ordinary ones, the malformed ones and the hostile ones -- and
# src/lib/wizard-input.test.ts asserts the port gives the same answers.
#
# Regenerate with `bin/rails wizard:fixture` if the validation changes; the
# frontend test fails until it is regenerated and committed.
namespace :wizard do
  FIXTURE = 'frontend/apps/site/src/lib/wizard-input.fixture.json'

  IPS = [
    '192.168.1.10', '10.0.0.1', '255.255.255.255', '0.0.0.0',
    '256.1.1.1', '1.2.3', '', ' ', 'not-an-ip', '192.168.1.10 ',
    '1.2.3.4; sf erase 0x0 0x1000000',
    '1.2.3.4 && sf write 0x82000000 0x0 0x800000',
    "1.2.3.4\nsf erase 0x0 0x1000000",
    '192.168.1.10;reboot',
  ].freeze

  MACS = [
    'aa:bb:cc:dd:ee:ff', 'AA-BB-CC-DD-EE-FF', 'Aa:Bb:Cc:Dd:Ee:Ff',
    '', 'aa:bb:cc:dd:ee', 'zz:bb:cc:dd:ee:ff', 'aa:bb:cc:dd:ee:ff; reboot',
    'aabbccddeeff',
  ].freeze

  desc 'Write what Rails accepts, for the frontend port to be held to'
  task fixture: :environment do
    require 'json'

    controller = Cameras::SocsController.new

    document = {
      'note' => 'Generated by bin/rails wizard:fixture. What Rails answers; the ' \
                'frontend port must answer the same.',
      'patterns' => {
        'ip' => ApplicationController.helpers.ipaddr_pattern,
        'mac' => ApplicationController.helpers.macaddr_pattern,
      },
      'ip' => IPS.to_h do |value|
        [value, controller.send(:well_formed, value, IP_ADDRESS_FORMAT, '192.168.1.10')]
      end,
      'mac' => MACS.to_h { |value| [value, controller.send(:normalised_mac, value)] },
    }

    File.write(Rails.root.join(FIXTURE), "#{JSON.pretty_generate(document)}\n")
    puts "wrote #{FIXTURE}"
  end
end
