# frozen_string_literal: true

# What Rails accepts, written down so the frontend can be held to it (#164).
#
# The wizard's input validation is the one piece of it that is duplicated
# rather than exported: the frontend has to decide what may go into a command
# before it renders one, and it cannot ask Rails at that moment. A duplicate is
# a thing that drifts, so this writes Rails' answers for a list of inputs --
# the ordinary ones, the malformed ones and the hostile ones -- and
# src/lib/wizard-input.test.ts asserts the port gives the same answers.
#
# Regenerate with `bin/rails wizard:fixture` if the validation changes; the
# frontend test fails until it is regenerated and committed.
namespace :wizard do
  FIXTURE = 'frontend/apps/site/src/lib/wizard-input.fixture.json'

  IPS = [
    '192.168.1.10', '10.0.0.1', '255.255.255.255', '0.0.0.0',
    '256.1.1.1', '1.2.3', '', ' ', 'not-an-ip', '192.168.1.10 ',
    '1.2.3.4; sf erase 0x0 0x1000000',
    '1.2.3.4 && sf write 0x82000000 0x0 0x800000',
    "1.2.3.4\nsf erase 0x0 0x1000000",
    '192.168.1.10;reboot',
  ].freeze

  MACS = [
    'aa:bb:cc:dd:ee:ff', 'AA-BB-CC-DD-EE-FF', 'Aa:Bb:Cc:Dd:Ee:Ff',
    '', 'aa:bb:cc:dd:ee', 'zz:bb:cc:dd:ee:ff', 'aa:bb:cc:dd:ee:ff; reboot',
    'aabbccddeeff',
  ].freeze

  desc 'Write what Rails accepts, for the frontend port to be held to'
  task fixture: :environment do
    require 'json'

    controller = Cameras::SocsController.new

    document = {
      'note' => 'Generated by bin/rails wizard:fixture. What Rails answers; the ' \
                'frontend port must answer the same.',
      'patterns' => {
        'ip' => ApplicationController.helpers.ipaddr_pattern,
        'mac' => ApplicationController.helpers.macaddr_pattern,
      },
      'ip' => IPS.to_h do |value|
        [value, controller.send(:well_formed, value, IP_ADDRESS_FORMAT, '192.168.1.10')]
      end,
      'mac' => MACS.to_h { |value| [value, controller.send(:normalised_mac, value)] },
    }

    File.write(Rails.root.join(FIXTURE), "#{JSON.pretty_generate(document)}\n")
    puts "wrote #{FIXTURE}"
  end
end

# What `update` settles on, for the frontend port to be held to (#164).
#
# The form can send a combination the page will not show as asked -- a 16MB
# layout on an 8MB chip, an edition upstream does not publish, Ultimate on a
# 5120KB rootfs partition -- and Rails moves each onto something it can render
# and says so. The static wizard has to reach the same answer: it decides which
# command block a visitor is shown, and a disagreement here is the two halves
# describing different installs of the same camera.
#
# Taken from Rails itself rather than restated. Each case is a real request;
# the settled configuration is read back out of the permanent link the page
# prints, which is exactly `Camera#permalink`, and the messages are read out of
# the rendered flash. Nothing about the rule is written down twice.
#
# Regenerate with `bin/rails wizard:settled` and commit the result;
# src/lib/wizard-result.parity.test.ts fails until it agrees.
namespace :wizard do
  SETTLED_FIXTURE = 'frontend/apps/site/src/lib/wizard-settled.fixture.json'

  # One per shape of answer, not one per SoC: a chip with no NOR build, the two
  # with a page of their own, and an ordinary one.
  SETTLED_SOCS = %w[hi3516ev300 hi3536dv100 ssc338q rv1126].freeze

  SETTLED_CASES = [
    { 'flash_type' => 'nor16m', 'partition_layout' => 'nor16m', 'firmware_version' => 'ultimate' },
    { 'flash_type' => 'nor8m', 'partition_layout' => 'nor8m', 'firmware_version' => 'ultimate' },
    { 'flash_type' => 'nor16m', 'partition_layout' => 'nor8m', 'firmware_version' => 'ultimate' },
    { 'flash_type' => 'nor8m', 'partition_layout' => 'nor16m', 'firmware_version' => 'lite' },
    { 'flash_type' => 'nor32m', 'partition_layout' => 'nor16m', 'firmware_version' => 'neo' },
    { 'flash_type' => 'nand', 'firmware_version' => 'ultimate' },
    { 'flash_type' => 'nand', 'firmware_version' => 'lite' },
    # Not a chip this site knows, which is what a hand-edited link looks like.
    { 'flash_type' => 'nor64m', 'firmware_version' => 'lite' },
    # Not an edition anybody publishes.
    { 'flash_type' => 'nor16m', 'partition_layout' => 'nor16m', 'firmware_version' => 'fabricator' },
    # A layout the chip cannot hold, which the page refuses rather than clamps.
    { 'flash_type' => 'nor8m', 'partition_layout' => 'nor16m', 'firmware_version' => 'ultimate' },
    # The addresses, which go inside a `setenv` and are the reason any of this
    # is validated at all.
    { 'camera_ip_address' => '1.2.3.4; sf erase 0x0 0x1000000',
      'server_ip_address' => '10.0.0.5', 'flash_type' => 'nor16m',
      'partition_layout' => 'nor16m', 'firmware_version' => 'lite' },
    { 'camera_mac_address' => 'AA-BB-CC-DD-EE-FF', 'flash_type' => 'nor16m',
      'partition_layout' => 'nor16m', 'firmware_version' => 'lite' },
    { 'camera_mac_address' => 'nope', 'flash_type' => 'nor16m',
      'partition_layout' => 'nor16m', 'firmware_version' => 'lite' },
  ].freeze

  desc 'Write what the wizard settles on, for the frontend port to be held to'
  task settled: :environment do
    require 'json'
    require Rails.root.join('lib/wizard_export')

    session = ActionDispatch::Integration::Session.new(Rails.application)

    socs = SETTLED_SOCS.filter_map do |urlname|
      soc = Soc.find_by_param(urlname)
      next unless soc

      [urlname, {
        'vendor' => soc.vendor.urlname,
        'editions' => Soc::FLASH_TYPES.to_h { |type| [type, soc.available_releases(type)] },
        'default_flash_chip' => soc.default_flash_chip,
        'special_pages' => Camera::FLASH_CHIP.filter_map do |flash_type|
          page = WizardExport.send(:special_page, soc, flash_type)
          [flash_type, page] if page
        end.to_h,
        'cases' => SETTLED_CASES.map do |asked|
          path = "/cameras/vendors/#{soc.vendor.urlname}/socs/#{urlname}"
          session.get(path, params: { camera: asked })
          body = session.response.body

          { 'asked' => asked }.merge(read_back(body))
        end,
      }]
    end.to_h

    document = {
      'note' => 'Generated by bin/rails wizard:settled. What Rails settles on; the ' \
                'frontend port must settle the same.',
      'socs' => socs,
    }

    File.write(Rails.root.join(SETTLED_FIXTURE), "#{JSON.pretty_generate(document)}\n")
    puts "wrote #{SETTLED_FIXTURE}: #{socs.size} SoC(s) x #{SETTLED_CASES.size} case(s)"
  end

  # The settled configuration, straight off the page: the permanent link is
  # `Camera#permalink` and carries every field the action decided.
  def read_back(body)
    page = body[%r{wiki/blob/master/en/(fpv-sigmastar|fpv-nvr)\.md}, 1]
    return { 'page' => page } if page

    {
      'permalink' => CGI.unescapeHTML(body[/href="(\?mac=[^"]*)"/, 1].to_s),
      'flashes' => body.scan(%r{<div class="mt-4 alert alert-(\w+)" role="alert">(.*?)</div>}m)
                       .map { |level, text| { 'level' => level, 'text' => CGI.unescapeHTML(text.strip) } },
    }
  end
end
