/**
 * Every address the bundle claims (#160).
 *
 * Addresses only, and deliberately no component imports: this list is what the
 * seam is made of, and the things that need it are not all page renderers.
 * `src/lib/site.build.test.ts` reads it to check the built tree, and a vitest
 * run has no Astro plugin -- importing a `.astro` file here would break every
 * consumer that only wanted to know what URLs exist.
 *
 * `path` is the address without a locale prefix, exactly as config/routes.rb
 * writes it -- including `/green_life`, which is the one marketing URL with an
 * underscore in it. It is not a typo and renaming it would break every inbound
 * link.
 *
 * Two kinds of address are absent on purpose:
 *
 *   * `/`, which stays on Rails. It is rendered per Accept-Language with
 *     `Vary: Accept-Language`, and a file serves one language to everyone. The
 *     locale roots `/ru/` and `/zh/` are in the bundle and are generated by
 *     ../pages/[locale]/index.astro, because a rest parameter cannot match an
 *     empty path.
 *   * the ~33 redirects, the two `410 Gone` routes and the catch-all, which
 *     are cheap, tested, and reached by falling through the seam.
 */
export interface PagePath {
  /** Locale-free address, leading slash, no trailing slash. */
  path: string;
  /** The catalogue key for <title>. */
  titleKey: string;
  /** The catalogue key for the meta description, when the page sets its own. */
  descriptionKey?: string;
  /** Keep it out of search results. The smoke page only. */
  noindex?: boolean;
}

export const PAGE_PATHS: PagePath[] = [
  // The diagnostic. Not a marketing page and never indexed, but it is an
  // address the bundle claims and it belongs in the same list as the rest --
  // deploy/static.sh, check-bundle.sh and check-config.sh all assert on it.
  { path: '/_smoke', titleKey: 'site.default_meta_description', noindex: true },

  { path: '/business', titleKey: 'pages.business.title' },
  { path: '/community', titleKey: 'pages.community.title' },
  { path: '/digital-twins', titleKey: 'pages.digital_twins.title' },
  { path: '/donate', titleKey: 'pages.donate.title' },
  { path: '/ecosystem', titleKey: 'pages.ecosystem.title' },
  { path: '/edge-ai', titleKey: 'pages.edge_ai.title', descriptionKey: 'pages.edge_ai.meta_description' },
  { path: '/get-started', titleKey: 'pages.get_started.title' },
  { path: '/green_life', titleKey: 'pages.green_life.title' },
  { path: '/isp-sensors', titleKey: 'pages.isp_sensors.title' },
  { path: '/low-latency', titleKey: 'pages.low_latency.title' },
  { path: '/majestic-endpoints', titleKey: 'pages.majestic_endpoints.title' },
  { path: '/merchandise', titleKey: 'pages.merchandise.title' },
  { path: '/our-team', titleKey: 'pages.our_team.title' },
  { path: '/privacy', titleKey: 'pages.privacy.title' },
  { path: '/reverse-engineering', titleKey: 'pages.reverse_engineering.title' },
  { path: '/stages-of-firmware-development', titleKey: 'pages.stages_of_firmware_development.title' },
  { path: '/teleoperation', titleKey: 'pages.teleoperation.title' },
  { path: '/turnkey-hardware', titleKey: 'pages.turnkey_hardware.title' },
  { path: '/utilities', titleKey: 'pages.utilities.title' },
  { path: '/video-encoding', titleKey: 'pages.video_encoding.title' },
  { path: '/web-interface', titleKey: 'pages.web_interface.title' },

  // The three web tools. Their addresses carry a directory that is not a page:
  // `/tools/` itself has no index.html and must not get one. check-bundle.sh
  // allows a directory that is not empty, and nginx's try_files misses it and
  // falls through to Rails, which 404s it exactly as it does today.
  { path: '/tools/firmware-partitions-calculation', titleKey: 'pages.firmware_partitions_calculation.title' },
  { path: '/tools/high-resolution-timer', titleKey: 'pages.high_resolution_timer.title' },
  { path: '/tools/qr-code-generator', titleKey: 'pages.qr_code_generator.title' },
];
