import type { KconfigGraph, Source } from "./types";

// ---------------------------------------------------------------------------
// Dependency closure
// ---------------------------------------------------------------------------


export type CloseDisableResult = {
  /** All symbols that end up disabled, including user picks + cascade. */
  disabled: Set<string>;
  /**
   * Symbols the user *wanted* disabled but can't be — because some
   * currently-set symbol *outside* the disable closure still hard-`select`s
   * them. Value = the still-enabled selectors blocking the disable.
   */
  blocked: Map<string, string[]>;
};

/**
 * Given the graph and the symbols the user wants to disable, compute the full
 * disable closure under select-cascade semantics.
 *
 * The rule, matching Kconfig's actual behaviour:
 *   • If you disable symbol X, every symbol that X `select`s becomes a candidate
 *     for disable too — but only IF nothing *else* still-enabled also selects it.
 *   • If something does, X's disable is *blocked*: telling Kconfig to drop X
 *     would silently leave it on, because Kconfig honours the surviving select.
 *
 * The function is pure (no mutation of inputs) and order-independent.
 */
export function closeDisable(
  graph: KconfigGraph,
  userWantsDisabled: ReadonlySet<string>,
): CloseDisableResult {
  const disabled = new Set<string>();
  const blocked = new Map<string, string[]>();

  // Iterate to fixed point: every pass adds anything newly disable-able given
  // the current `disabled` set. Bounded by symbol count, so worst-case O(n²).
  let changed = true;
  let pending = new Set(userWantsDisabled);

  while (changed) {
    changed = false;
    const nextPending = new Set<string>();

    for (const name of pending) {
      const sym = graph.symbols[name];
      if (!sym) {
        // Unknown symbol → silently drop. Could be a stale URL query
        // pointing at a symbol that no longer exists in this build.
        continue;
      }

      // Surviving (currently-set ∧ not-yet-disabled-by-us ∧ not-the-target)
      // hard-selectors of `name`. If any exist, we can't disable `name`.
      const survivors = sym.selected_by.filter(
        (s) => !disabled.has(s) && s !== name,
      );

      if (survivors.length > 0) {
        blocked.set(name, survivors);
        continue;
      }

      if (!disabled.has(name)) {
        disabled.add(name);
        changed = true;
        // Cascade: this symbol's `selects` become candidates next pass.
        for (const target of sym.selects) {
          if (!disabled.has(target)) nextPending.add(target);
        }
      }
    }

    pending = nextPending;
    if (pending.size > 0) changed = true;
  }

  // Re-check blocked: a symbol previously blocked may now be unblocked because
  // all its survivors ended up disabled later in the cascade.
  let reUnblocked = true;
  while (reUnblocked) {
    reUnblocked = false;
    for (const [name, survivors] of blocked) {
      const stillSurviving = survivors.filter(
        (s) => !disabled.has(s) && s !== name,
      );
      if (stillSurviving.length === 0) {
        blocked.delete(name);
        disabled.add(name);
        reUnblocked = true;
        const sym = graph.symbols[name];
        if (sym) {
          for (const target of sym.selects) {
            if (!disabled.has(target)) {
              // Re-evaluate this target next sweep.
              blocked.delete(target);
            }
          }
        }
      } else if (stillSurviving.length !== survivors.length) {
        blocked.set(name, stillSurviving);
      }
    }
  }

  return { disabled, blocked };
}

/**
 * Render the disabled set as a Buildroot defconfig fragment that the user can
 * append to their board defconfig. Each line `# BR2_PACKAGE_FOO is not set`
 * follows Kconfig's serialisation convention. Output is deterministic
 * (sorted by symbol name) so two browsers with the same selection produce
 * byte-identical files.
 */
export function defconfigFragment(
  graph: KconfigGraph,
  disabled: ReadonlySet<string>,
): string {
  const lines: string[] = [];
  lines.push("# Generated by https://openipc.org/firmware-explorer");
  lines.push(`# Board: ${graph.board}-${graph.variant}`);
  lines.push("# Append these lines to your board defconfig, then re-run defconfig.");
  lines.push("");

  const sorted = [...disabled].sort();
  for (const name of sorted) {
    // Only emit symbols we know about — protects against URL-injected garbage.
    if (graph.symbols[name]) {
      lines.push(`# ${name} is not set`);
    }
  }
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Build-request flow — pre-fill a GitHub issue, in the repository that builds
// the platform, with the user's defconfig fragment. A maintainer dispatches
// that repository's build-one.yml with the issue's number; it applies the
// fragment's `# BR2_... is not set` lines, builds, and replies on the issue.
// ---------------------------------------------------------------------------

/**
 * GitHub's new-issue URL accepts ~8000 characters total before truncation.
 * Reserve a margin for the title + query keys + URL-encoding overhead;
 * defconfig fragments above this threshold are clipped with a `<truncated>`
 * marker rather than producing a silently broken URL.
 */
export const BUILD_REQUEST_MAX_BODY = 6000;
export const BUILD_REQUEST_REPOS: Record<Source, string> = {
  firmware: "OpenIPC/firmware",
  builder: "OpenIPC/builder",
};
export const BUILD_REQUEST_LABEL = "build-request";

/**
 * The name build-one.yml takes for a platform: its defconfig's, without
 * `_defconfig`. Builder platforms already are that (`ssc337_lite_tiandy-…`);
 * firmware publishes `ssc337-ultimate` for the `ssc337_ultimate` defconfig.
 */
export function buildPlatform(source: Source, platform: string): string {
  return source === "firmware" ? platform.replace(/^([a-z0-9]+)-/, "$1_") : platform;
}

export type BuildRequestInput = {
  source: Source;
  platform: string;
  graph: KconfigGraph;
  disabled: ReadonlySet<string>;
  savingsBytes: number;
  newHeadroomKb: number | null;
  shareUrl: string;
};

export type BuildRequest = {
  title: string;
  body: string;
  url: string;
  truncated: boolean;
};

/**
 * Compose a GitHub issue URL, on the repository that builds the platform,
 * pre-filled with the user's defconfig fragment and a short context block. Pure function:
 * given identical inputs, returns byte-identical output (modulo the
 * shareUrl that the caller passes through).
 */
export function buildRequest(input: BuildRequestInput): BuildRequest {
  const { source, platform, graph, disabled, savingsBytes, newHeadroomKb, shareUrl } = input;
  const repo = BUILD_REQUEST_REPOS[source];
  const target = buildPlatform(source, platform);

  const title = `Build request: ${target} (${disabled.size} symbols off)`;

  const fragment = defconfigFragment(graph, disabled);

  const summary = [
    `**Platform**: \`${target}\``,
    `**Disabled symbols**: ${disabled.size}`,
    `**Estimated rootfs savings**: ~${Math.round(savingsBytes / 1024)} KB`,
    newHeadroomKb !== null
      ? `**Projected rootfs headroom**: ≈ ${newHeadroomKb} KB`
      : null,
    `**Composed at**: ${shareUrl}`,
  ]
    .filter((s): s is string => s !== null)
    .join("\n");

  // What happens next, for the maintainer and the requester alike: only the
  // `is not set` lines are applied (build-one refuses anything else), and a
  // symbol another package selects stays on -- the reply says which.
  const note =
    `<!-- Submitted from openipc.org/firmware-explorer. To build it: dispatch ` +
    `build-one.yml in ${repo} with platform=${target} and request_issue=<this issue's number>. -->\n` +
    "A maintainer builds this with the fragment below applied and posts the image here. " +
    "A symbol that another package selects stays enabled; the reply will name any.";

  let truncated = false;
  let fragmentBlock = fragment;
  // Cap body so the URL stays under GitHub's input limit.
  const overhead =
    title.length + summary.length + note.length + 64 /* fenced-code + headings */;
  const fragmentBudget = BUILD_REQUEST_MAX_BODY - overhead;
  if (fragmentBlock.length > fragmentBudget) {
    fragmentBlock = fragmentBlock.slice(0, Math.max(0, fragmentBudget - 32)) +
      "\n# … truncated to fit URL budget …\n";
    truncated = true;
  }

  const body = [
    note,
    "",
    "## Summary",
    summary,
    "",
    "## Defconfig fragment",
    "```",
    fragmentBlock.replace(/\n$/, ""),
    "```",
  ].join("\n");

  const params = new URLSearchParams();
  params.set("labels", BUILD_REQUEST_LABEL);
  params.set("title", title);
  params.set("body", body);
  const url = `https://github.com/${repo}/issues/new?${params.toString()}`;

  return { title, body, url, truncated };
}
