# frozen_string_literal: true

require 'test_helper'

# A response rendered for a signed-in admin must never be stored by the shared
# cache in front of the app.
#
# snapshots/show renders the uploading camera's IP and MAC address when an
# admin is signed in, and nginx caches that URL for 300s keyed on the path
# alone -- no cookie -- so without a marker the admin's copy is handed to every
# anonymous visitor until the entry expires. The same template is reached at
# /open-wall/camera/<id>, cached for 60s.
#
# nginx cannot detect this for itself: Devise keeps the admin identity inside
# the same encrypted session cookie every visitor receives, so no variable it
# can see tells the two apart. The header asserted here is the whole mechanism
# -- `proxy_no_cache $upstream_http_x_admin_view` in
# deploy/nginx/sites-available/org.openipc is the other half, and neither is
# any use without the other.
class AdminCacheIsolationTest < ActionDispatch::IntegrationTest
  include Devise::Test::IntegrationHelpers

  # The smallest thing the view will build image URLs from: SOI, a JFIF APP0
  # and EOI. Nothing decodes it here -- the variants are generated by a job
  # that the test queue adapter never runs -- so it only has to identify as a
  # JPEG. Validations are skipped because the size floor is not what is under
  # test.
  MINIMAL_JPEG = "\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xFF\xD9".b

  setup do
    @snapshot = Snapshot.new(mac_address: '00:11:22:33:44:55', ip_address: '203.0.113.9',
                             soc: 'gk7205v300', sensor: 'imx307')
    @snapshot.file.attach(io: StringIO.new(MINIMAL_JPEG), filename: 'snapshot.jpg',
                          content_type: 'image/jpeg')
    @snapshot.save!(validate: false)
  end

  test 'an anonymous snapshot page is cacheable and shows no uploader details' do
    get snapshot_path(@snapshot)

    assert_response :success
    assert_nil response.headers['X-Admin-View'],
               'an anonymous response must be storable by the shared cache'
    assert_no_match(/203\.0\.113\.9/, response.body)
    assert_no_match(/00:11:22:33:44:55/, response.body)
  end

  test "an admin's snapshot page carries the marker that keeps it out of the cache" do
    sign_in admins(:one)

    get snapshot_path(@snapshot)

    assert_response :success
    assert_equal '1', response.headers['X-Admin-View'],
                 'without this header nginx stores the admin rendering and serves it to everyone'
  end

  test 'the uploader details an admin sees are the ones that must not be cached' do
    sign_in admins(:one)

    get snapshot_path(@snapshot)

    assert_match(/203\.0\.113\.9/, response.body, 'the admin view is expected to show the IP')
    assert_match(/00:11:22:33:44:55/, response.body, 'and the MAC')
  end

  # /open-wall/camera/<id> renders the same template through a different route,
  # and is cached by a different location block.
  test 'the per-camera page carries the marker too' do
    sign_in admins(:one)

    get openwall_camera_path(@snapshot.mac_address_dec)

    assert_response :success
    assert_equal '1', response.headers['X-Admin-View']
  end

  test 'the marker is absent everywhere for anonymous visitors' do
    get '/'
    assert_nil response.headers['X-Admin-View']

    get '/open-wall'
    assert_nil response.headers['X-Admin-View']
  end

  # The other cache in front of an admin page is the one inside the visitor's
  # own browser. Turbo keeps a snapshot of every page it leaves and restores it
  # from memory on Back, without asking the server -- so signing out would stop
  # taking these pages off the screen, which is exactly what a full load's
  # `must-revalidate` used to guarantee. Every admin page renders through this
  # layout, so one tag covers all of them.
  test 'admin pages are not kept in the browser-side Turbo snapshot cache' do
    sign_in admins(:one)
    get admin_socs_path

    assert_response :success
    assert_select 'head meta[name=?][content=?]', 'turbo-cache-control', 'no-cache'
  end
end
