#!/usr/bin/env python3
"""Regenerate deploy/nginx/conf.d/openipc-blocked-nets.list.

The list is every network announced by an autonomous system registered in a
country whose providers cannot reach openipc.org intact -- today Russia, where
the TSPU freezes a TLS connection to the origin's hosting network after the
first 20-odd kilobytes. nginx answers those networks with a 301 to the mirror
(conf.d/openipc-blocked-nets.conf).

    deploy/blocked-nets.py                 # fetch iptoasn.com's table, rewrite the list
    deploy/blocked-nets.py --from FILE     # from a downloaded ip2asn-combined.tsv(.gz)

The table maps each announced range to the AS that announces it and the
country that AS is registered in. Ranges are turned into CIDRs and collapsed,
so the file nginx loads is as short as the address space allows. Run it by
hand when the list should catch up with routing, and commit the result: the
file is reviewed like any other configuration, and nothing on the host fetches
it.
"""

import argparse
import gzip
import io
import ipaddress
import os
import sys
import urllib.request
from datetime import datetime, timezone

SOURCE = "https://iptoasn.com/data/ip2asn-combined.tsv.gz"
COUNTRIES = ("RU",)
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "nginx", "conf.d", "openipc-blocked-nets.list")


def read_table(path):
    if path is None:
        with urllib.request.urlopen(SOURCE, timeout=120) as r:
            raw = r.read()
    else:
        with open(path, "rb") as f:
            raw = f.read()
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    return io.StringIO(raw.decode("utf-8", "replace"))


def networks(table, countries):
    v4, v6, asns = [], [], set()
    for line in table:
        fields = line.rstrip("\n").split("\t")
        if len(fields) < 4:
            continue
        start, end, asn, country = fields[:4]
        # AS 0 is "not routed": address space nobody announces.
        if country not in countries or asn == "0":
            continue
        asns.add(asn)
        first, last = ipaddress.ip_address(start), ipaddress.ip_address(end)
        (v4 if first.version == 4 else v6).extend(ipaddress.summarize_address_range(first, last))
    return list(ipaddress.collapse_addresses(v4)), list(ipaddress.collapse_addresses(v6)), asns


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--from", dest="src", help="a downloaded ip2asn-combined.tsv or .tsv.gz")
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()

    v4, v6, asns = networks(read_table(args.src), COUNTRIES)
    if not v4 or len(asns) < 1000:
        sys.exit(f"blocked-nets: {len(asns)} ASes and {len(v4)} IPv4 networks; the table looks wrong, nothing written")

    day = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    tmp = args.out + ".tmp"
    with open(tmp, "w") as f:
        f.write(f"# Generated by deploy/blocked-nets.py from {SOURCE} on {day}.\n")
        f.write(f"# Every network announced by an AS registered in {', '.join(COUNTRIES)}: "
                f"{len(asns)} ASes, {len(v4)} IPv4 and {len(v6)} IPv6 networks.\n")
        f.write("# Do not edit; rerun the script. What it is for: openipc-blocked-nets.conf.\n")
        for n in v4 + v6:
            f.write(f"{n} 1;\n")
    os.replace(tmp, args.out)
    print(f"{args.out}: {len(asns)} ASes, {len(v4)} IPv4 + {len(v6)} IPv6 networks")


if __name__ == "__main__":
    main()
