# frozen_string_literal: true

require 'json'

# What Rails answers, written down so a port can be held to it (#291).
#
# Two of the upload's rules are not ours to restate. Which bytes count as an
# image is Marcel's table, reached through ActiveStorage's identification --
# Go's http.DetectContentType does not know `ftyp heic`, so a port using it
# would refuse every HEIF upload, and the only symptom would be one camera going
# dark. And the MAC rule is a regex in config/initializers/000_settings.rb that
# a port will be tempted to rewrite. So neither is described here: Rails is
# asked, for a list of inputs, and its verdicts are committed as JSON the
# conformance suite replays against whatever is serving.
#
# The same arrangement as lib/tasks/wizard_fixture.rake. Regenerate with
# `bin/rails conformance:fixtures`; test/conformance_fixtures_test.rb fails
# while the committed files disagree with what Rails says today.
module ConformanceFixtures
  DIR = 'test/conformance/fixtures'

  # First bytes of a file, by what they claim to be. Each is padded to 12 KB so
  # the size rule is not also being tested.
  PREFIXES = {
    'jpeg' => "\xFF\xD8\xFF\xE0\x00\x10JFIF\x00".b,
    'jpeg-exif' => "\xFF\xD8\xFF\xE1\x00\x10Exif\x00\x00".b,
    'png' => "\x89PNG\r\n\x1A\n\x00\x00\x00\rIHDR".b,
    'gif89a' => 'GIF89a'.b,
    'webp' => "RIFF\x00\x30\x00\x00WEBPVP8 ".b,
    'bmp' => 'BM'.b,
    'tiff-le' => "II*\x00".b,
    'heic' => "#{[24].pack('N')}ftypheic#{[0].pack('N')}mif1heic".b,
    'heix' => "#{[24].pack('N')}ftypheix#{[0].pack('N')}mif1heix".b,
    'mif1' => "#{[24].pack('N')}ftypmif1#{[0].pack('N')}mif1heic".b,
    'avif' => "#{[24].pack('N')}ftypavif#{[0].pack('N')}mif1avif".b,
    'mp4' => "#{[24].pack('N')}ftypisom#{[0].pack('N')}isomiso2".b,
    'svg' => '<svg xmlns="http://www.w3.org/2000/svg">'.b,
    'pdf' => '%PDF-1.4'.b,
    'zip' => "PK\x03\x04".b,
    'html' => '<!DOCTYPE html><html>'.b,
    'text' => 'not an image at all '.b,
    'zeros' => "\x00\x00\x00\x00".b,
    'binary' => "\x13\x37\xC0\xDE\xFA\xCE\xB0\x0C".b
  }.freeze

  DECLARED = ['image/jpeg', 'image/heic', 'image/png', 'application/octet-stream', 'text/plain', nil].freeze

  FILENAMES = %w[snapshot.jpg snapshot.heic snapshot].freeze

  SIZE = 12_288

  # Not the all-zero MAC: production blacklists it, and a deployment's
  # blacklist is not the format rule. It is the 403 test's MAC there instead.
  MACS = [
    'aa:bb:cc:dd:ee:ff', 'AA:BB:CC:DD:EE:FF', 'Aa:Bb:Cc:Dd:Ee:Ff', 'aa-bb-cc-dd-ee-ff',
    'aa:bb-cc:dd-ee:ff', '12:34:56:78:9a:bc', 'ff:ff:ff:ff:ff:ff', '02:c0:f0:12:34:56',
    '', ' ', 'aa:bb:cc:dd:ee', 'aa:bb:cc:dd:ee:ff:00', 'aabbccddeeff', 'aabb.ccdd.eeff',
    'a:bb:cc:dd:ee:ff', 'aa:bb:cc:dd:ee:f', 'aaa:bb:cc:dd:ee:ff', 'gg:bb:cc:dd:ee:ff',
    'aa:bb:cc:dd:ee:ff ', ' aa:bb:cc:dd:ee:ff', "aa:bb:cc:dd:ee:ff\n", "aa:bb:cc:dd:ee:ff\nx",
    'aa bb cc dd ee ff', 'aa:bb:cc:dd:ee:ff;reboot', 'ａａ:bb:cc:dd:ee:ff'
  ].freeze

  # Stands in for a MAC in the content-type corpus. Invalid on purpose: with
  # it, the upload is refused whatever the file, so replaying a verdict never
  # stores anything -- and the refusal still lists every file error, because
  # validations do not stop at the first failure.
  PROBE_MAC = 'not-a-mac'

  class << self
    def content_types
      cases = PREFIXES.flat_map do |name, prefix|
        DECLARED.product(FILENAMES).map do |declared, filename|
          errors = file_errors(prefix.b + ("\x00".b * (SIZE - prefix.bytesize)), declared, filename)
          { 'prefix' => name, 'declared' => declared, 'filename' => filename,
            'accepted' => errors.empty?, 'file_errors' => errors }
        end
      end
      { 'note' => note('conformance:fixtures'), 'size' => SIZE, 'probe_mac' => PROBE_MAC,
        'mac_error' => mac_errors(PROBE_MAC), 'prefixes' => PREFIXES.transform_values { |b| b.unpack1('H*') },
        'cases' => cases }
    end

    def mac_addresses
      { 'note' => note('conformance:fixtures'),
        'cases' => MACS.map { |mac| mac_case(mac) } }
    end

    def documents
      { 'content_types' => content_types, 'mac_addresses' => mac_addresses }
    end

    def json(document)
      "#{JSON.pretty_generate(document)}\n"
    end

    def path(name)
      Rails.root.join(DIR, "#{name}.json")
    end

    def write
      documents.each { |name, document| File.write(path(name), json(document)) }
    end

    private

    def note(task)
      "Generated by bin/rails #{task}. What Rails answers; any server on this endpoint must answer the same."
    end

    # Through the same door the controller uses: an uploaded file, attached,
    # so ActiveStorage identifies it from the bytes, the name and the declared
    # type exactly as it does for a camera.
    def file_errors(bytes, declared, filename)
      io = Tempfile.new(['conformance', File.extname(filename)], binmode: true)
      io.write(bytes)
      io.rewind
      upload = ActionDispatch::Http::UploadedFile.new(tempfile: io, filename: filename, type: declared)
      snapshot = Snapshot.new(file: upload, mac_address: 'aa:bb:cc:dd:ee:ff')
      snapshot.validate
      snapshot.errors.full_messages_for(:file)
    ensure
      io&.close!
    end

    def mac_case(mac)
      errors = mac_errors(mac)
      { 'mac' => mac, 'accepted' => errors.empty?, 'mac_errors' => errors }
    end

    def mac_errors(mac)
      snapshot = Snapshot.new(mac_address: mac)
      snapshot.validate
      snapshot.errors.full_messages_for(:mac_address)
    end
  end
end
