# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Vendor.delete_all
Vendor.create([
                { id: 1, name: 'Ambarella', full_name: 'Ambarella, Inc.', website_url: 'https://www.ambarella.com/' },
                { id: 2, name: 'Anyka', full_name: 'Guangzhou Anyka Microelectronics Co., Ltd.', website_url: 'http://www.anyka.com/' },
                { id: 3, name: 'Fullhan', full_name: 'Shanghai Fullhan Microelectonics Co., Ltd.', website_url: 'https://www.fullhan.com/' },
                { id: 4, name: 'Goke', full_name: 'Hunan Goke Microelectronics Co., Ltd.', website_url: 'http://www.goke.com/' },
                { id: 5, name: 'Grain Media', full_name: 'Grain Media Ltd.', website_url: 'https://www.grainmedia.co.uk/' },
                { id: 6, name: 'HiSilicon', full_name: 'HiSilicon (Shanghai) Technologies Co., Ltd.', website_url: 'https://www.hisilicon.com/' },
                { id: 7, name: 'Ingenic', full_name: 'Ingenic Semiconductor Co.,Ltd.', website_url: 'http://www.ingenic.com.cn/' },
                { id: 8, name: 'MStar', full_name: 'MStar Semiconductor, Inc', website_url: 'https://www.mstarsemi.com/' },
                { id: 9, name: 'Novatek', full_name: 'Novatek Microelectronics Corporation', website_url: 'https://www.novatek.com.tw/' },
                { id: 10, name: 'SigmaStar', full_name: 'SigmaStar Technology Ltd.', website_url: 'http://www.sigmastarsemi.com/' },
                { id: 11, name: 'Xiongmai', full_name: 'Hangzhou Xiongmai Technology Co.,Ltd.', website_url: 'https://www.xiongmaitech.com/' },
                { id: 12, name: 'AltaSens', full_name: 'AltaSens, Inc.', website_url: 'http://www.altasens.com/' },
                { id: 13, name: 'Aptina', full_name: 'Aptina Imaging Corporation', website_url: 'https://www.onsemi.com/' },
                { id: 14, name: 'Himax', full_name: 'Himax Technologies, Inc.', website_url: 'https://www.himax.com.tw/' },
                { id: 15, name: 'OmniVision', full_name: 'OmniVision Technologies Inc.', website_url: 'https://www.ovt.com/' },
                { id: 16, name: 'Panasonic', full_name: 'Panasonic Industry Co., Ltd.', website_url: 'https://www.panasonic.com/' },
                { id: 17, name: 'Pixelplus', full_name: 'Pixelplus Co., Ltd.', website_url: 'http://www.pixelplus.com/' },
                { id: 18, name: 'SmartSens', full_name: 'SmartSens Technology (Shanghai) Co., Ltd.', website_url: 'https://www.smartsenstech.com/' },
                { id: 19, name: 'SOI', full_name: 'Silicon Optronics, Inc', website_url: 'https://www.soinc.com.tw/' },
                { id: 20, name: 'Sony', full_name: 'Sony Semiconductor Solutions', website_url: 'https://www.sony-semicon.co.jp/' },
                { id: 21, name: 'Nuvoton', full_name: 'Nuvoton Technology Corporation Japan', website_url: 'https://www.nuvoton.com/' },
                { id: 22, name: 'Glaxycore', full_name: 'Galaxycore Inc', website_url: 'https://www.gcoreinc.com/' },
              ])

Soc.delete_all
Soc.create([
             { vendor_id: 1, model: 'S2L', status: 'rnd', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 1, model: 'S3L', status: 'wip', load_address: '', uboot_filename: '', linux_filename: 'openipc.ambarella-s3l-br.tgz' },
             { vendor_id: 2, model: 'AK3916EV300', status: 'neq', load_address: '', uboot_filename: '', linux_filename: 'openipc.ak3916ev300-br.tgz' },
             { vendor_id: 2, model: 'AK3916EV301', status: 'rnd', load_address: '', uboot_filename: '', linux_filename: 'openipc.ak3918ev200-br.tgz' },
             { vendor_id: 2, model: 'AK3918EV200', status: 'hlp', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 2, model: 'AK3918EV300', status: 'neq', load_address: '', uboot_filename: '', linux_filename: 'openipc.ak3918ev300-br.tgz' },
             { vendor_id: 2, model: 'AK3918EV330', status: 'rnd', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 3, model: 'FH8626V100', status: 'hlp', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 3, model: 'FH8632V100', status: 'neq', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 3, model: 'FH8652V100', status: 'hlp', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 3, model: 'FH8852V100', status: 'wip', load_address: '', uboot_filename: '', linux_filename: 'openipc.fh8852v100-br.tgz' },
             { vendor_id: 3, model: 'FH8852V200', status: 'wip', load_address: '0xA1000000', uboot_filename: '', linux_filename: 'openipc.fh8852v200-br.tgz' },
             { vendor_id: 3, model: 'FH8852V210', status: 'neq', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 3, model: 'FH8856V100', status: 'neq', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 3, model: 'FH8856V200', status: 'wip', load_address: '', uboot_filename: '', linux_filename: 'openipc.fh8856v200-br.tgz' },
             { vendor_id: 3, model: 'FH8856V210', status: 'neq', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 3, model: 'FH8858V200', status: 'neq', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 3, model: 'FH8858V210', status: 'neq', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 4, model: 'GK7102S', status: 'rnd', load_address: '0xC1000000', uboot_filename: '', linux_filename: '' },
             { vendor_id: 4, model: 'GK7202V300', status: 'done', load_address: '0x42000000', uboot_filename: 'u-boot-gk7202v300-universal.bin', linux_filename: 'openipc.gk7202v300-br.tgz' },
             { vendor_id: 4, model: 'GK7205V200', status: 'done', load_address: '0x42000000', uboot_filename: 'u-boot-gk7205v200-universal.bin', linux_filename: 'openipc.gk7205v200-br.tgz' },
             { vendor_id: 4, model: 'GK7205V210', status: 'done', load_address: '0x42000000', uboot_filename: '', linux_filename: 'openipc.gk7205v210-br.tgz' },
             { vendor_id: 4, model: 'GK7205V300', status: 'done', load_address: '0x42000000', uboot_filename: 'u-boot-gk7205v300-universal.bin', linux_filename: 'openipc.gk7205v300-br.tgz' },
             { vendor_id: 4, model: 'GK7605V100', status: 'done', load_address: '0x42000000', uboot_filename: 'u-boot-gk7605v100-universal.bin', linux_filename: 'openipc.gk7605v100-br.tgz' },
             { vendor_id: 5, model: 'GM8135', status: 'neq', load_address: '', uboot_filename: '', linux_filename: '' },
             { vendor_id: 5, model: 'GM8136', status: 'mvp', load_address: '', uboot_filename: '', linux_filename: 'openipc.gm8136-br.tgz' },
             { vendor_id: 6, model: 'HI3516AV100', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516av100-universal.bin', linux_filename: 'openipc.hi3516av100-br.tgz' },
             { vendor_id: 6, model: 'HI3516AV200', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516av200-universal.bin', linux_filename: 'openipc.hi3516av200-br.tgz' },
             { vendor_id: 6, model: 'HI3516AV300', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516av300-universal.bin', linux_filename: 'openipc.hi3516av300-br.tgz' },
             { vendor_id: 6, model: 'HI3516CV100', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516cv100-universal.bin', linux_filename: 'openipc.hi3516cv100-br.tgz' },
             { vendor_id: 6, model: 'HI3516CV200', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516cv200-universal.bin', linux_filename: 'openipc.hi3516cv200-br.tgz' },
             { vendor_id: 6, model: 'HI3516CV300', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516cv300-universal.bin', linux_filename: 'openipc.hi3516cv300-br.tgz' },
             { vendor_id: 6, model: 'HI3516CV500', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516cv500-universal.bin', linux_filename: 'openipc.hi3516cv500-br.tgz' },
             { vendor_id: 6, model: 'HI3516DV100', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516dv100-universal.bin', linux_filename: 'openipc.hi3516dv100-br.tgz' },
             { vendor_id: 6, model: 'HI3516DV200', status: 'done', load_address: '0x42000000', uboot_filename: 'u-boot-hi3516dv200-universal.bin', linux_filename: 'openipc.hi3516dv200-br.tgz' },
             { vendor_id: 6, model: 'HI3516DV300', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516dv300-universal.bin', linux_filename: 'openipc.hi3516dv300-br.tgz' },
             { vendor_id: 6, model: 'HI3516EV100', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3516ev100-universal.bin', linux_filename: 'openipc.hi3516ev100-br.tgz' },
             { vendor_id: 6, model: 'HI3516EV200', status: 'done', load_address: '0x42000000', uboot_filename: 'u-boot-hi3516ev200-universal.bin', linux_filename: 'openipc.hi3516ev200-br.tgz' },
             { vendor_id: 6, model: 'HI3516EV300', status: 'done', load_address: '0x42000000', uboot_filename: 'u-boot-hi3516ev300-universal.bin', linux_filename: 'openipc.hi3516ev300-br.tgz' },
             { vendor_id: 6, model: 'HI3518CV100', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3518cv100-universal.bin', linux_filename: 'openipc.hi3518cv100-br.tgz' },
             { vendor_id: 6, model: 'HI3518EV100', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3518ev100-universal.bin', linux_filename: 'openipc.hi3518ev100-br.tgz' },
             { vendor_id: 6, model: 'HI3518EV200', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3518ev200-universal.bin', linux_filename: 'openipc.hi3518ev200-br.tgz' },
             { vendor_id: 6, model: 'HI3518EV201', status: 'done', load_address: '0x82000000', uboot_filename: '', linux_filename: '' },
             { vendor_id: 6, model: 'HI3518EV300', status: 'done', load_address: '0x42000000', uboot_filename: 'u-boot-hi3518ev300-universal.bin', linux_filename: 'openipc.hi3518ev300-br.tgz' },
             { vendor_id: 6, model: 'HI3519V101', status: 'done', load_address: '0x82000000', uboot_filename: 'u-boot-hi3519v101-universal.bin', linux_filename: 'openipc.hi3519v101-br.tgz' },
             { vendor_id: 6, model: 'HI3520DV100', status: '', load_address: '0x82000000', uboot_filename: '', linux_filename: '' },
             { vendor_id: 6, model: 'HI3520DV200', status: '', load_address: '0x82000000', uboot_filename: '', linux_filename: '' },
             { vendor_id: 7, model: 'T10', status: 'mvp', load_address: '0x80600000', uboot_filename: 'u-boot-t10-universal.bin', linux_filename: 'openipc.t10-br.tgz' },
             { vendor_id: 7, model: 'T20', status: 'mvp', load_address: '0x80600000', uboot_filename: 'u-boot-t20-universal.bin', linux_filename: 'openipc.t20-br.tgz' },
             { vendor_id: 7, model: 'T21', status: 'mvp', load_address: '0x80600000', uboot_filename: '', linux_filename: 'openipc.t21-br.tgz' },
             { vendor_id: 7, model: 'T31', status: 'mvp', load_address: '0x80600000', uboot_filename: '', linux_filename: 'openipc.t31-br.tgz' },
             { vendor_id: 8, model: 'MSC313E', status: 'wip', load_address: '0x21000000', uboot_filename: 'u-boot-msc313e-universal.bin', linux_filename: 'openipc.msc313e-br.tgz' },
             { vendor_id: 8, model: 'MSC316DC', status: 'wip', load_address: '0x21000000', uboot_filename: '', linux_filename: 'openipc.msc316dc-br.tgz' },
             { vendor_id: 8, model: 'MSC316DM', status: 'wip', load_address: '0x21000000', uboot_filename: '', linux_filename: 'openipc.msc316dm-br.tgz' },
             { vendor_id: 9, model: 'NT98562', status: 'wip', load_address: '', uboot_filename: '', linux_filename: 'openipc.nt98562-br.tgz' },
             { vendor_id: 9, model: 'NT98566', status: 'wip', load_address: '', uboot_filename: '', linux_filename: 'openipc.nt98566-br.tgz' },
             { vendor_id: 10, model: 'SSC325', status: 'rnd', load_address: '', uboot_filename: '', linux_filename: 'openipc.ssc325-br.tgz' },
             { vendor_id: 10, model: 'SSC335', status: 'mvp', load_address: '0x21000000', uboot_filename: '', linux_filename: 'openipc.ssc335-br.tgz' },
             { vendor_id: 10, model: 'SSC335DE', status: 'rnd', load_address: '0x21000000', uboot_filename: '', linux_filename: 'openipc.ssc335de-br.tgz' },
             { vendor_id: 10, model: 'SSC337', status: 'mvp', load_address: '0x21000000', uboot_filename: '', linux_filename: 'openipc.ssc337-br.tgz' },
             { vendor_id: 10, model: 'SSC337DE', status: 'rnd', load_address: '0x21000000', uboot_filename: '', linux_filename: 'openipc.ssc337de-br.tgz' },
             { vendor_id: 11, model: 'XM510', status: 'mvp', load_address: '', uboot_filename: '', linux_filename: 'openipc.xm510-br.tgz' },
             { vendor_id: 11, model: 'XM530', status: 'mvp', load_address: '', uboot_filename: '', linux_filename: 'openipc.xm530-br.tgz' },
             { vendor_id: 11, model: 'XM550', status: 'mvp', load_address: '', uboot_filename: '', linux_filename: 'openipc.xm550-br.tgz' },
           ])

# { vendor_id: 13, model: '9p031', mode: '3m' },
# { vendor_id: 13, model: '9p031', mode: '5m' },
# { vendor_id: 13, model: '9p031', mode: '720p' },
# { vendor_id: 13, model: 'ar0237', mode: 'soc_v3' },
# { vendor_id: 13, model: 'ar0331', mode: '3m_lvds_30fps' },
# { vendor_id: 13, model: 'ar0331', mode: '60fps' },
# { vendor_id: 13, model: 'ar0331', mode: 'lvds' },
# { vendor_id: 15, model: 'ov2718', mode: '2a' },
# { vendor_id: 15, model: 'ov2718', mode: '2a__soc_v3' },
# { vendor_id: 15, model: 'ov2718', mode: 'soc_v3' },
# { vendor_id: 15, model: 'ov5658', mode: '5m' },
# { vendor_id: 15, model: 'ov9712', mode: 'plus' },
# { vendor_id: 16, model: 'mn34220', mode: 'mipi' },
# { vendor_id: 19, model: 'f22', mode: 'soc_v3' },
# { vendor_id: 19, model: 'f23', mode: 'soc_v4' },
# { vendor_id: 20, model: 'imx036', mode: '3m' },
# { vendor_id: 20, model: 'imx178', mode: '37M' },
# { vendor_id: 20, model: 'imx290', mode: 'soc_v3' },
# { vendor_id: 20, model: 'imx307', mode: 'soc_v3' },
# { vendor_id: 20, model: 'imx323', mode: 'soc_v3' },
# { vendor_id: 20, model: 'imx385', mode: 'soc_v3' },

# SmartSens sensor series
# -----------------------
# SC - Traditional Product
# CS - Consumer Series
# AI - Advanced Imaging Series
# AT - Automotive Series
# GS - Global Shutter Series
# IoT - Internet of Things Series
# SL - Star-light Series

Sensor.delete_all
Sensor.create([
                { vendor_id: 12, model: '3372' },
                { vendor_id: 13, model: 'mt9m034', optical_format: '1/3−inch (6 mm)', imager_size: '', active_pixels: '1280x960', pixel_size: '3.75μm', color_filter_array: 'RGB Bayer or Monochrome', max_fps_full: '45', max_fps_vga: '60', responsivity: '5.48 V/lux-sec', snr_max: '43.9dB', pixel_dynamic_range: '>115dB',voltage: '1.8-2.8', power_consumption: '280W', operating_temp: '-30+70', packaging: '10x10mm 48-pin iLCC' },
                { vendor_id: 13, model: 'mt9p031', optical_format: '1/2.5-inch 4:3', imager_size: '5.70mm(H) x 4.28mm(V), 7.13mm diagonal', active_pixels: '2592x1944', pixel_size: '2.2μm', color_filter_array: 'RGB Bayer pattern', max_data_rate: '96 Mp/s at 96 MHz (2.8V I/O), 48 Mp/s at 48 MHz (1.8V I/O)', max_fps_full: '14', max_fps_vga: '53', adc_resolution: '12-bit, on-chip', responsivity: '1.4 V/lux-sec (550nm)', pixel_dynamic_range: '70.1dB', snr_max: '38.1dB', voltage: '1.8−3.1', power_consumption: '381mW', operating_temp: '-30+70', packaging: '48-pin iLCC, die'},
                { vendor_id: 13, model: 'ar0130' },
                { vendor_id: 13, model: 'ar0140' },
                { vendor_id: 13, model: 'ar0230' },
                { vendor_id: 13, model: 'ar0237' },
                { vendor_id: 13, model: 'ar0330' },
                { vendor_id: 13, model: 'ar0331' },
                { vendor_id: 13, model: 'mt9p006' },
                { vendor_id: 14, model: '1375' },
                { vendor_id: 15, model: 'ov2715' },
                { vendor_id: 15, model: 'ov2718' },
                { vendor_id: 15, model: 'ov4689' },
                { vendor_id: 15, model: 'ov5658' },
                { vendor_id: 15, model: 'ov9712' },
                { vendor_id: 15, model: 'ov9732' },
                { vendor_id: 15, model: 'ov9750' },
                { vendor_id: 15, model: 'ov9752' },
                { vendor_id: 16, model: 'mn34031' },
                { vendor_id: 16, model: 'mn34041' },
                { vendor_id: 16, model: 'mn34220' },
                { vendor_id: 16, model: 'mn34222' },
                { vendor_id: 17, model: '3100k' },

                ## SmartSense
                { vendor_id: 18, model: 'SC1135' },
                { vendor_id: 18, model: 'SC1145' },
                { vendor_id: 18, model: 'SC2035' },
                { vendor_id: 18, model: 'SC2135' },
                { vendor_id: 18, model: 'SC2235' },

                ### SOI
                # ???
                { vendor_id: 19, model: 'F22' },
                { vendor_id: 19, model: 'F23' },
                { vendor_id: 19, model: 'H22' },
                # 1MP
                { vendor_id: 19, model: 'JX-H62',  resolution: '720P', process: 'FSI', pixel_size: '',     optical_format: '1/4"', frame_rate: '60fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-H63',  resolution: '720P', process: 'FSI', pixel_size: '2.8',  optical_format: '1/4"', frame_rate: '60fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-H68',  resolution: '960P', process: 'FSI', pixel_size: '3.75', optical_format: '1/3"', frame_rate: '60fps', interface: 'Mipi/DVP' },
                # 2MP
                { vendor_id: 19, model: 'JX-F28',  resolution: '1080P', process: 'FSI', pixel_size: '2.2', optical_format: '1/4"',   frame_rate: '60fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-F32',  resolution: '1080P', process: 'FSI', pixel_size: '3',   optical_format: '1/2.7"', frame_rate: '60fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-F35',  resolution: '1080P', process: 'FSI', pixel_size: '3',   optical_format: '1/2.7"', frame_rate: '60fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-F352', resolution: '1080P', process: 'BSI', pixel_size: '2.9', optical_format: '1/2.8"', frame_rate: '60fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-F37P', resolution: '1080P', process: 'FSI', pixel_size: '2.7', optical_format: '1/3"',   frame_rate: '30fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-F38',  resolution: '1080P', process: 'FSI', pixel_size: '2.5', optical_format: '1/3.2"', frame_rate: '30fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-F39',  resolution: '1080P', process: 'FSI', pixel_size: '3.75', optical_format: '1/2"',  frame_rate: '60fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-F51',  resolution: '1:1 1080P', process: 'FSI', pixel_size: '2.7', optical_format: '1/3"', frame_rate: '30fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-F53',  resolution: '1080P', process: 'FSI', pixel_size: '2.9', optical_format: '1/2.9"', frame_rate: '30fps', interface: 'Mipi/DVP' },
                # 3-5MP
                { vendor_id: 19, model: 'JX-Q03',  resolution: '3M', process: 'FSI', pixel_size: '2.5', optical_format: '1/2.7"', frame_rate: '30fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-K04',  resolution: '4M', process: 'FSI', pixel_size: '2.2', optical_format: '1/2.7"', frame_rate: '30/60fps', interface: 'Mipi/DVP' },
                { vendor_id: 19, model: 'JX-K05',  resolution: '5M', process: 'FSI', pixel_size: '2.2', optical_format: '1/2.5"', frame_rate: '30fps', interface: 'Mipi/DVP' },
                # 8MP
                { vendor_id: 19, model: 'JX-K08',  resolution: '8M', process: 'BSI', pixel_size: '1.62', optical_format: '1/2.5"', frame_rate: '30fps', interface: 'Mipi/DVP' },
                # Global Shutter Sensor
                { vendor_id: 19, model: 'JX-S02',  resolution: '1.3M', process: '', pixel_size: '4.8', optical_format: '1/2"', frame_rate: '200fps', interface: 'LVDS/Mipi/DVP' },

                { vendor_id: 20, model: 'icx692' },
                { vendor_id: 20, model: 'imx036' },
                { vendor_id: 20, model: 'imx104' },
                { vendor_id: 20, model: 'imx117' },
                { vendor_id: 20, model: 'imx122' },
                { vendor_id: 20, model: 'imx123' },
                { vendor_id: 20, model: 'imx136' },
                { vendor_id: 20, model: 'imx138' },
                { vendor_id: 20, model: 'imx178' },
                { vendor_id: 20, model: 'imx185' },
                { vendor_id: 20, model: 'imx222' },
                { vendor_id: 20, model: 'imx225' },
                { vendor_id: 20, model: 'imx236' },
                { vendor_id: 20, model: 'imx290' },
                { vendor_id: 20, model: 'imx307' },
                { vendor_id: 20, model: 'imx323' },
                { vendor_id: 20, model: 'imx323' },
                { vendor_id: 20, model: 'imx385' },
                { vendor_id: 22, model: 'GC4653' },
              ])
